###

#@name auth
POST http://localhost:3000/api/auth/register
POST http://localhost:3000/api/auth/login

# @name getAllUsers
GET http://localhost:3000/api/users
Content-Type: application/json
###
# @name getUserById
GET http://localhost:3000/api/users/id
Content-Type: application/json
# @name editUser
PUT http://localhost:3000/api/users/edit/id
Content-Type: application/json
# @name deleteUser
PUT http://localhost:3000/api/users/delete/id

@name getAllProduits
GET http://localhost:3000/api/produits
@name getAllProduitById
GET http://localhost:3000/api/produits/id
@name createProduit
POST http://localhost:3000/api/produits/add
@name editProduit
PUT http://localhost:3000/api/produits/edit/id
@name deleteProduit
delete http://localhost:3000/api/produits/delete/id
